name = "CalendarPuzzle"
uuid = "bb41bd2c-8411-42e7-b372-733a1cd982c0"
authors = ["GOTOH Shunsuke <antimon2.me@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
